from core.imports import st

col1, col2, col3 = st.columns([1, 2, 1])
with col2:
    st.image("assets/URO_logo.png")
    
st.title("URO: University Resource Optimization")

#Introduction of the system
st.write(
    f"University Resource Optimization is a system designed to analyze **classroom usage** and **energy/electrical cost** and provide optimization recommendation.\n"
    f"\nOptimization is the process of finding the best possible solution (maximum profit, minimum cost, highest efficiency)\n"
    f"from a set of available options, by using mathematical models and algorithms to improve a system, process, or design, while satisfying\n"
    f"specific limitations or constraints. It's about making something as perfect or effective as possible, whether it's a business operation,\n"
    f"a software program, or an engineering structure.\n"
)

# ==============================================================================
# PENJELASAN (Untuk Supervisor):
# Isu Definisi: "Sistem awak ni bagi cadangan (recommendations) sahaja. Kenapa guna 
# nama 'Optimization'? Optimization selalunya guna algoritma matematik kompleks."
# JAWAPAN: Optimization di sini merujuk kepada konsep "Rule-Based Heuristic Optimization". 
# Ia bertindak sebagai Sistem Sokongan Keputusan (Decision Support System) yang memproses 
# data analisis deskriptif lalu menjana satu set pelan tindakan (actionable insights) yang 
# optimum untuk pihak pengurusan. Walaupun ia tidak menyelesaikan persamaan matematik 
# kompleks, ia tetap 'mengoptimumkan' penggunaan ruang kelas berdasarkan syarat-syarat.
# ==============================================================================

if st.session_state['user_role'] == "IT Staff":
    st.write(f"""
        You can **upload classroom** and **energy** data files, to help the management analyze the data and generate insights to identify areas for
        improvement. The system also provides **data management** features, allowing you to **view data records, edit batch name**, or **delete data records**
        to maintain an organized database for analysis. Overall, the University Resource Optimization system aims to help educational institutions optimize
        their resources and reduce costs while maintaining a high level of service quality.
    """)
    
    st.divider()
    st.info("""
    ### 🚀 Quick Start Guide for IT Staff
    Follow these simple steps to get started:
    1. **Go to 'Upload Files'**: Click it on the left sidebar.
    2. **Upload Data**: Select your classroom and energy files.
    3. **Save Batch**: Choose the semester and year for a name (e.g., 'Sem 1 2026') and click 'Save Data'.
    4. **Manage Data**: Use the 'Manage Data' tab if you need to edit or delete records.
    """)
elif st.session_state['user_role'] == "Manager":
    st.write(f"""
        You can view the **analysis results** and **optimization recommendations** of **classroom** and **energy** data generated by the system.
        The system provides **insights** into **classroom usage** and **energy/electrical cost** patterns, helping you make informed decisions about
        **resource allocation** and **cost management**. Overall, the University Resource Optimization system aims to help educational institutions optimize
        their resources and reduce costs while maintaining a high level of service quality.
    """)
    
    st.divider()
    st.info("""
    ### 🚀 Quick Start Guide for Managers
    Follow these simple steps to get started:
    1. **Select Data Batch**: Look at the dropdown menu in the left sidebar. It will appear in other pages except this one.
    2. **Load Data**: Click the 'Load Data' button right below it.
    3. **View Results**: Once loaded, navigate to the **Analysis** or **Optimization** pages to see the insights!
    """)
