# pip install streamlit | streamlit is use to create the UI. to open streamlit, run 'python -m streamlit run main.py'. to close, press 'ctrl + c' at terminal
import streamlit as st

col1, col2, col3 = st.columns(3)
with col2:
    st.image("images/URO_logo.png")
    
st.title("URO: University Resource Optimization")

#Introduction of the system
st.write(
    f"University Resource Optimization is a system designed to analyze classroom usage and energy/electrical cost and provide optimization recommendation.\n"
    f"\nOptimization is the process of finding the best possible solution (maximum profit, minimum cost, highest efficiency)\n"
    f"from a set of available options, by using mathematical models and algorithms to improve a system, process, or design, while satisfying\n"
    f"specific limitations or constraints. It's about making something as perfect or effective as possible, whether it's a business operation,\n"
    f"a software program, or an engineering structure.\n"
)

if st.session_state['user_role'] == "IT Staff":
    st.write(f"""
        As an IT staff, you can upload classroom usage and energy cost data files, to help the management analyze the data and generate insights to
        identify areas for improvement. The system also provides data management features, allowing you to clear old data and maintain an organized database for analysis.
        Overall, the University Resource Optimization system aims to help educational institutions optimize their resources and reduce costs while
        maintaining a high level of service quality.
    """)
elif st.session_state['user_role'] == "Manager":
    st.write(f"""
        As a Manager, you can view the analysis results and optimization recommendations generated by the system. The system provides insights
        into classroom usage and energy/electrical cost patterns, helping you make informed decisions about resource allocation and cost management.
        Overall, the University Resource Optimization system aims to help educational institutions optimize their resources and reduce costs
        while maintaining a high level of service quality.
    """)

