[theme]
# Inherit from Streamlit's default light or dark theme ("light" or "dark")
base = "light" 
textColor = "#000000ff"
font = "sans serif"
baseFontSize = 18 # Sets the root font size in pixels

[client]
showSidebarNavigation = true
